<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>formAnimaux</title>
</head>
<body>
<header>
		<nav>
			
		</nav>
	</header>
	<main>
		<div class="forms">
			<div class="form">
				<div class ="signup">
					<div class="heading">Ajouter un animal </div>
					<form action="" method= "post" autocomplete="off">
						<label  for="champFamille">famille de l'animal</label>
                        <select name= "champFamille" id="champFamille">
                            <option value="0">Sélectionner</option>
                            <?php
								
								foreach($familles as $famille){
									if($famille->getId() == $unAnimal->getFamille()->getID()){
										print('<option value="'.$famille->getId().'" selected>'.$famille->getType().'</option>');
									}else{
										print('<option value="'.$famille->getId().'">'.$famille->getType().'</option>');

									}
								}

                            ?>
                        </select>
						<input type="text" name="champRace" id="champRace" placeholder="Race">
						<input type="text" name="champNom" id="champNom" placeholder="Nom">
                        <label  for="champSexe">Sexe de l'animal</label>
                        <select name= "champSexe" id="champSexe">
                            <option value="0">Sélectionner</option>
                            <?php
                            
                            ?>
                        </select>
						<input type="text" name="champDateNaissance" id="champDateNaissance" placeholder="Date de Naissance">
						<input type="text" name="champDateDeDeces" id="champDateDeDeces" placeholder="Date de deces">
						<input type="int" name="champPoid" id="champPoid" placeholder="Poid">
					    <button class="buttonForms" id="btnInscrip" type="submit">Inscription</button>
					</form>
				</div>
			</div>
		</div>
	</main>
    
</body>
</html>