<?php
	ini_set('display_errors', 'on');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="public/styles/style.css" type="text/css"/>
    <title>PetVet - Inscription</title>
</head>
<body>
	<header>
		<nav>
			<?php require "includes/partials/navbarNoCo.php"; ?>
		</nav>
	</header>
	<main>
        <div class="forms">
            <div class="form">
				<div class="login">
					<div class="heading">Connectez-vous ! </div>
					<form action ="" method="POST">
						<input type="text" name= "champEmail"id= "champEmail" placeholder="Email">
						<input type="password" name="champPassword" id= "champPassword" placeholder="Password">
						<button class="buttonForms" type="submit">Connexion</button>
					</form>
					<?= $message ?? '' ?>
				</div>
			</div>
        </div>
	</main>
	