<!DOCTYPE html>
<html lang="en">
<head>
	<?php require_once "includes/partials/page_head.php"; ?>
    <title>PetVet - Contact</title>
</head>
<body>
	<header>
		<nav>
			<?php 
				if(empty($_SESSION)){
					require "includes/partials/navbarNoCo.php";
				}else{
					require "includes/partials/navbarCo.php";
				} 
			?>
		</nav>
	</header>
<main>
	<div class="forms-contact">
		<div class ="contact">
			<div class="heading-contact">Vous avez une question ? </div>
			<form action ="" method = "post" autocomplete="off">
			<input type="text" id="champNom" placeholder="Nom">
			<input type="email" id="champEmail" placeholder="Email">
			<input type="text" id="champObjet" placeholder="Objet de la demande">
			<textarea id="champDemande" placeholder="Ecrivez votre demande ici"></textarea>
			<button class="buttonForms">Envoyez le message</button>
		</form>
		</div>
	</div>  
</main> 
</body>
<script src="script.js"></script>
</html>
  


	


