<?php
	ini_set('display_errors', 'on');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="public/styles/style.css" type="text/css"/>
    <title>PetVet - Connexion</title>
</head>
<body>
	<header>
		<nav>
			<?php require "includes/partials/navbarNoCo.php"; ?>
		</nav>
	</header>
	<main>
		<div class="forms">
			<div class="form">
				<div class ="signup">
					<div class="heading">Pas encore inscrit ? </div>
					<form action="" method= "post" autocomplete="off">
						<input type="text" name="champNom" id="champNom" placeholder="Nom">
						<input type="text" name="champPrenom" id="champPrenom" placeholder="Prenom">
						<input type="email" name="champEmail" id="champEmail" placeholder="Email">
						<input type="password" name="champPassword" id="champPassword" placeholder="Password">
						<input type="number" name="champNumAdresse" id="champNumAdresse" placeholder="Numero d'adresse">
						<input type="text" name="champNomAdresse" id="champNomAdresse" placeholder="Adresse">
						<input type="number" name="champCodePostal" id="champCodePostal" placeholder="Code Postal">
						<input type="text" name="champVille" id="champVille" placeholder="Ville">
						<button class="buttonForms" id="btnInscrip" type="submit">Inscription</button>
					</form>
				</div>
			</div>
		</div>
	</main>
	

    
</body>
<script src="../../../public/scripts/script.js"></script>
</html>
  


	


