<?php
	ini_set('display_errors', 'on');
?>
<!DOCTYPE html>
<html lang="fr">
<head>
	<?php require_once "includes/partials/page_head.php"; ?>
    <title>PetVet - Modifier vos Animaux</title>
</head>
<body>
<header>
		<nav>
		<?php require "includes/partials/navbarCo.php"; ?>
		</nav>
	</header>
	<main>
		<div class="forms">
			<div class="form">
				<div class ="signup">
					<div class="heading">Modifier un animal </div>
					<form action="" method= "post" autocomplete="off">
						<label  for="champFamille">Famille de l'animal</label>
                        <select name= "champFamille" id="champFamille">
                            <option value="0">Sélectionner</option>
                            <?php
								foreach($lesFamilles as $famille){
									if($famille->getId() == $unAnimal->getFamille()->getId()){
										print('<option value="'.$famille->getId().'" selected>'.$famille->getType().'</option>');
									}else{
										print('<option value="'.$famille->getId().'">'.$famille->getType().'</option>');
									}
								}
                            ?>
                        </select>
						<input type="text" name="champNom" id="champNom" value="<?= $unAnimal->getNom() ?>">
                        <label  for="champSexe">Sexe de l'animal</label>
                        <select name= "champSexe" id="champSexe">
                            <option value="0">Sélectionner</option>
                            <?php
								foreach($lesSexes as $sexe){
									if($sexe->getId() == $unAnimal->getSexe()->getId()){
										print('<option value="'.$sexe->getId().'" selected>'.$sexe->getSexe().'</option>');
									}else{
										print('<option value="'.$sexe->getId().'">'.$sexe->getSexe().'</option>');
									}
								}
                            ?>
                        </select>
						<input type="date" name="champDateNaissance" id="champDateNaissance" value="<?= $unAnimal->getDateNaissance()->format('Y-m-d')?>">
						<input type="int" name="champPoids" id="champPoids" value="<?= $unAnimal->getPoids()->getPoids() ?>">
					    <button class="buttonForms"  type="submit">Modifier</button>
					</form>
				</div>
			</div>
		</div>
	</main>
    
</body>
</html>