<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/public/styles/style.css" type="text/css" />
    <title>form connexion inscription</title>
</head>
<body>
<div class="forms">
	  <div class="form">
		<div class ="signup">
		  <div class="heading">Pas encore inscrit ? </div>
		  <form action ="" method = "POST" autocomplete="off">
			<input type="text" id="champNom" placeholder="Nom">
			<input type="email" id="champEmail" placeholder="Email">
			<input type="password" id="champPassword" placeholder="Password">
			<button class="button">Inscription</button>
		   </div>
		</form>
	  </div>
	  <div class="form">
		<div class="login">
		  <div class="heading">Connectez-vous ! </div>
		  <form action ="" method="POST" autocomplete="off">
			<input type="text" id= "champEmail" placeholder="Email">
			<input type="password" id= "champPassword" placeholder="Password">
			<button class="button" type=submit>Connexion</button>
		  </div>
		</form>
	  </div>
	</div>
    
</body>
<script src="script.js"></script>
</html>
  


	


