<?php
	ini_set('display_errors', 'on');
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<?php require_once "includes/partials/page_head.php"; ?>
    <title>PetVet - Connexion</title>
</head>
<body>
	<header>
		<nav>
		<?php require "includes/partials/navbarNoCo.php"; ?>
		</nav>
	</header>
	<main>
		<div class="forms">
			<div class="form">
				<div class ="signup">
					<div class="heading">Pas encore inscrit ? </div>
					<form action="" method= "post" autocomplete="off">
						<input type="text" name="champNom" id="champNom" data-required data-name="champNom" value=""placeholder="Nom" >
						<input type="text" name="champPrenom" id="champPrenom" data-required data-name="champPrenom" value="" placeholder="Prénom" >
						<input type="email" name="champEmail" id="champEmail" data-required data-name="champEmail" value="" placeholder="Email" >
						<?= $message ?? '' ?>
						<input type="password" name="champPassword" id="champPassword" autocomplete="off" data-required data-name="champPassword data-length="8" placeholder="Password (Maj + 8 caract mini + 1 caract spé )" >
						<input type="number" name="champNumAdresse" id="champNumAdresse" data-required data-name="champNumAdresse" value="" placeholder="Numéro d'adresse" >
						<input type="text" name="champNomAdresse" id="champNomAdresse" data-required data-name="champNomAdresse" value="" placeholder="Adresse" >
						<input type="number" name="champCodePostal" id="champCodePostal" data-required data-name="champCodePostal" value="" placeholder="Code Postal" >
						<input type="text" name="champVille" id="champVille" data-required data-name="champVille" value="" placeholder="Ville" >
						<button class="buttonForms" id="btnInscrip" type="submit">Inscription</button>
					</form>
				</div>
			</div>
		</div>
	</main>
	

    
</body>
<script type="module" src="public/scripts/script_inscription.js"></script></html>
  


	


