<?php
	ini_set('display_errors', 'on');
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<?php require_once "includes/partials/page_head.php"; ?>
    <title>Ajouter un nouvel animal</title>
</head>
<body>
<header>
	<nav>
		<?php 
			require "includes/partials/navbarCo.php"; 
		?>
	</nav>
</header>
	<main>
		<div class="forms">
			<div class="form">
				<div class ="signup">
					<div class="heading">Ajouter un animal </div>
					<form action="" method= "post" autocomplete="off">
						<label  for="champFamille">Famille de l'animal</label>
                        <select name= "champFamille" id="champFamille"required="required">
                            <option value="0">Sélectionner</option>
                            <?php
								foreach($lesFamilles as $famille){
									if($famille->getId() == $unAnimal->getFamille()->getId()){
										print('<option value="'.$famille->getId().'" selected>'.$famille->getType().'</option>');
										 
									}else{
										print('<option value="'.$famille->getId().'">'.$famille->getType().'</option>');
									}
								}
                            ?>
                        </select>
						<input type="text" name="champNom" id="champNom" placeholder="Nom"required="required">
                        <label  for="champSexe">Sexe de l'animal</label>
                        <select name= "champSexe" id="champSexe"required="required">
                            <option value="0">Sélectionner</option>
                            <?php
								foreach($lesSexes as $sexe){
									if($sexe->getId() == $unAnimal->getSexe()->getId()){
										print('<option value="'.$sexe->getId().'" selected>'.$sexe->getSexe().'</option>');
									}else{
										print('<option value="'.$sexe->getId().'">'.$sexe->getSexe().'</option>');
									}
								}
                            ?>
                        </select>
						<input type="date" name="champDateNaissance" id="champDateNaissance" placeholder="Date de Naissance"required="required">
						<input type="int" name="champPoids" id="champPoids" placeholder="Poids" required="required">
					    <button class="buttonForms" id="btnInscrip" type="submit">Ajouter</button>
					</form>
				</div>
			</div>
		</div>
	</main>
    
</body>

</html>