<!DOCTYPE html>
<html lang="fr">
<head>
    <?php require_once "includes/partials/page_head.php"; ?>
    <title>PetVet - Informations Utiles</title>
</head>
<body>
    <header>
        <nav>
            <?php 
                require "includes/partials/navbarCo.php"; 
            ?>
        </nav>

    </header>
	
    <main class="infosContainer">
        <section class="urgenceVeto">
        </section>
        <section class="infosPoison">
        </section>
        <h2>Urgence chat</h2>
        <section class="urgenceChat">
        </section>
        <h2>Urgence chien</h2>
        <section class="urgenceChien">
        </section>
    </main>
    <footer>
        
        <?php
        require "includes/partials/footer.php";
        ?>

    </footer>
</body>
<script type="text/javascript" src="public/scripts/infosUtile.js"></script>
</html>