<?php
	ini_set('display_errors', 'on');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="public/styles/style.css" type="text/css"/>

	<title>Vos animaux</title>
</head>
<body>
    <header>
		<nav>
			<?php require "includes/partials/navbarCo.php"; ?>
		</nav>
    </header>
	<main>
		<div class="containerAnimaux">
			<div class="cardAnimaux">
				<div class="boxAnimaux">
					<div class="contentAnimaux">
						<a class="listButton" href="index.php?page=animaux&action=add">Ajouter un animal</a>
					</div>
				</div>
			</div>
		<?php
			foreach ($lesAnimaux as $unAnimal) {
				?>
				<div class="cardAnimaux">
					<div class="boxAnimaux">
						<div class="contentAnimaux">
							<h3><?=$unAnimal->getNom()?></h3>
							<p>Famille : <?= $unAnimal->getFamille()->getType()?></p>
							<p>Sexe : <?= $unAnimal->getSexe()->getSexe()?></p>
							<p>Né(e) le : <?=$unAnimal->getDateNaissance()->format('d/m/Y')?></p>
							<p>Poids : <?=$unAnimal->getPoids()->getPoids()?> kg</p>

							
							<button class="listButton modifAnimalBtn" form=<?=$unAnimal->getId()?>>Modifier</button>
							<button class="listButton deleteAnimalBtn" form=<?=$unAnimal->getId()?>>Supprimer</button>
						</div>
					</div>
				</div>
		<?php
			}
		?>
		</div>
		
    </main>
	<footer>
        <?php
        require "includes/partials/footer.php";
        ?>
    </footer>
</body>
<script type="text/javascript" src="public/scripts/scriptFormAnimaux.js"></script>
</html>