<!DOCTYPE html>
<html lang="en">
<head>
    <?php require_once "includes/partials/page_head.php"; ?>
    <title>PetVet</title>
</head>
<body>
    <header>
        <?php
            require "includes/partials/header.php";
        ?>
        
        <nav>
            <?php 
            require "includes/partials/navbarNoCo.php";
        ?>
        </nav>
    </header>
    <main>
        <article>
            <?php
            require "includes/partials/cardAcceuil.php";
            ?>
        </article>

    </main>
    <footer>
        <?php
        require "includes/partials/footer.php";
        ?>

    </footer>
    
</body>
</html>
