<?php
	ini_set('display_errors', 'on');
	require_once "includes/core/globals.php";
?>
<!DOCTYPE html>
<html lang="fr">
<head>
	<?php require "includes/partials/page_head.phtml"; ?>
</head>
<body>
	<main>
		<nav>
			<?php require_once "includes/partials/navbar.phtml"; ?>
		</nav>
		<header>
			<h1>Titre de ma page d'accueil</h1>
		</header>
		<pre>
			<?php 
				print_r($personne1);
			?>
		</pre>
		<footer>
			<?php require_once "includes/partials/footer.phtml"; ?>
		</footer>
	</main>
</body>
</html>